version: '3.7'

services:
  vault:
      image: vault:latest
      container_name: product_vault_local
      volumes:
        - ./volumes/vault-file:/vault/file
      ports:
        - "8200:8200/tcp"
      environment:
        VAULT_DEV_ROOT_TOKEN_ID: ${VAULT_TOKEN}
        VAULT_DEV_LISTEN_ADDRESS: '0.0.0.0:8200'
        VAULT_ADDR: 'http://0.0.0.0:8200'
      cap_add:
        - IPC_LOCK
      entrypoint: "vault server -dev"
  redis:
      image: redis:6.2-alpine
      container_name: product_redis_local
      restart: always
      ports:
        - '6379:6379'
      command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_TOKEN}
      volumes:
        - ./volumes/redis-data:/var/lib/redis
        - ./volumes/redis.conf:/usr/local/etc/redis/redis.conf
      environment:
        - REDIS_REPLICATION_MODE=master
  postgres:
    image: postgres
    container_name: product_postgres_local
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=product
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5492:5432'
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data